version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/projectmanager
    docker:
      - image: circleci/ruby:2.6.5-stretch
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATCH: vendor/bundle
          RAILS_ENV: test
    steps:
      # Database Setup
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # RSpec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                        --format RspecJunitFormatter \
                        --out test_results/rspec.xml \
                        --format progress \
                        $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Saving time results
      - store_test_results:
          path: test_results