version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: ruby:2.6.5
      - image: node:8.16.2
      - image: sqlite3:1.4
    environment:
      RAILS_ENV: test
      RACK_ENV: test
    steps:
      - checkout
      - run:
        name: Install System Dependencies
        command: apt-get update -qq && apt-get install -y build-essential nodejs
      - restore_cache:
        key: dependency-cache-{{ checksum "Gemfile.lock" }}
      - run:
        name: Install Dependencies
        command: apt-get install -y libicu52 && apt-get install -y libicu-dev bundle install --path vendor/bundle --frozen --jobs=4 --retry=3 --without development bin/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Create DB
          command: cp config/database.yml.ci config/database.yml export RAILS_ENV="test" export RACK_ENV="test" bundle exec rake db:create db:schema:load --trace
      - run:
          name: Run Tests
          command: bundle exec rake test
      - run:
          name: Report coverage to CodeClimate
          command: bundle exec codeclimate-test-reporter
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_test_results:
          path: /tmp/circle-junit