version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/projectmanager
    docker:
      - image: circleci/ruby:2.6.5-stretch
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATCH: vendor/bundle
          RAILS_ENV: test
    steps:
      # Bundle Install
      - restore_cache:
          keys:
            - projectmanager-bundle-v2-{{ checksum "Gemfile.lock" }}
            - projectmanager-bundle-v2-
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      - save_cache:
          key: projectmanager-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Yarn/Webpack Install
      - restore_cache:
          keys:
            - projectmanager-yarn-{{ checksum "yarn.lock" }}
            - projectmanager-yarn-
      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: projectmanager-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # Database Setup
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      # RSpec in parallel
      - run: |
          bundle exec rspec --profile 10 \
                        --format RspecJunitFormatter \
                        --out test_results/rspec.xml \
                        --format progress \
                        $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Saving time results
      - store_test_results:
          path: test_results